// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ApiPaymets.Database.CompiledModels
{
    public partial class ApiDbContextModel
    {
        private ApiDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("a7232cd6-6e75-4577-8b0d-8196e6fe3754"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var payment = PaymentEntityType.Create(this);

            PaymentEntityType.CreateAnnotations(payment);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
