// <auto-generated />
using ApiPaymets.Database;
using ApiPaymets.Database.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApiDbContext), typeof(ApiDbContextModel))]
